/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#ededf9",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "surface-bright": "#faf8ff",
        "on-primary-fixed": "#00174b",
        "inverse-on-surface": "#f0f0fb",
        "critical-red": "#EF4444",
        "on-secondary": "#ffffff",
        "inverse-primary": "#b4c5ff",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-background": "#191b23",
        "on-error": "#ffffff",
        "surface-off-white": "#F8FAFC",
        "on-tertiary-container": "#ffede6",
        "on-secondary-fixed": "#002113",
        "slate-dark": "#1E293B",
        "on-secondary-fixed-variant": "#005236",
        "secondary": "#006c49",
        "warning-orange": "#F59E0B",
        "on-primary-container": "#eeefff",
        "primary-container": "#2563eb",
        "secondary-fixed": "#6ffbbe",
        "surface-dim": "#d9d9e5",
        "on-secondary-container": "#00714d",
        "background": "#faf8ff",
        "tertiary": "#943700",
        "primary-fixed-dim": "#b4c5ff",
        "primary-fixed": "#dbe1ff",
        "surface-container-highest": "#e1e2ed",
        "on-surface-variant": "#434655",
        "secondary-container": "#6cf8bb",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#4edea3",
        "surface-container-lowest": "#ffffff",
        "slate-muted": "#64748B",
        "inverse-surface": "#2e3039",
        "outline": "#737686",
        "tertiary-fixed": "#ffdbcd",
        "on-primary": "#ffffff",
        "surface-container-low": "#f3f3fe",
        "surface": "#faf8ff",
        "on-primary-fixed-variant": "#003ea8",
        "on-tertiary-fixed": "#360f00",
        "surface-container-high": "#e7e7f3",
        "surface-variant": "#e1e2ed",
        "on-error-container": "#93000a",
        "primary": "#004ac6",
        "tertiary-container": "#bc4800",
        "surface-tint": "#0053db",
        "tertiary-fixed-dim": "#ffb596",
        "outline-variant": "#c3c6d7",
        "on-surface": "#191b23",
        "mint-bg": "#F0FDFA"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "margin-desktop": "32px",
        "stack-md": "16px",
        "stack-lg": "24px",
        "margin-mobile": "16px",
        "sidebar-width": "260px",
        "container-max": "1440px",
        "stack-sm": "8px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "label-sm": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "display-lg": ["Inter"]
      },
      fontSize: {
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "display-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
