spring.application.name=Hospital_Management_System

# MySQL Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/hospital}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:sarang@123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Config
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Ensure data.sql runs after tables are created
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
server.port=8080

spring.sql.init.data-locations=classpath:data.sql
